language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != '7.0' && "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then php vendor/bin/ocula code-coverage:upload --format=php-clover coverage.clover; fi